### PR TITLE
Fix #6179 Initializing default logger

### LINKED ISSUE #6179: logger instantiates itself with default settings, causing crash on server environments that do not allow file write permissions
### Issue Description

When you import the parse-server sdk, the logger file instantiates the file logger with default settings, causing the nodejs application to crash if the file system doesn't allow write permissions. This is irrespective of instantiating parse-server with custom config. The problem appears to be in the logger.js file on the line:

`let logger = defaultLogger();`

### Steps to reproduce

1. Create a 'logs' directory with read only permission at the base of the project directory './logs'
2. Import the parse-server module with express running
3. The nodejs/express server will crash because the './logs' directory is read only.
 
### Expected Results

The server should run and the logger should only instantiate once I instantiate the parse-server with optional config settings

### Actual Outcome

The logger is instantiated even before I instantiate the parse-server and have a chance to pass my own config settings causing a crash if write permissions are not allowed

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 3.9.0
  - Operating System:     Parse server hosted by google app engine nodejs standard environment
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Google App Engine Standard Environment, or localhost without file write permissions

### Logs/Trace
`
{
 insertId: "5dbc64ea00010957b7762996"  
 labels: {
  clone_id: "00c61b117c37e953a744445117cca35dda5c28e7dddc8cd7e6c4936a7ef8cda1c3d442bca9"   
 }
 logName: "projects/communityroot/logs/stderr"  
 receiveTimestamp: "2019-11-01T17:01:30.156658889Z"  
 resource: {
  labels: {
   module_id: "api"    
   project_id: "communityroot"    
   version_id: "20191101t120829"    
   zone: "us17"    
  }
  type: "gae_app"   
 }
 textPayload: "Error: EROFS: read-only file system, mkdir '/srv/logs/'
    at Object.mkdirSync (fs.js:757:3)
    at /srv/node_modules/file-stream-rotator/FileStreamRotator.js:515:20
    at Array.reduce (<anonymous>)
    at mkDirForFile (/srv/node_modules/file-stream-rotator/FileStreamRotator.js:503:27)
    at Object.FileStreamRotator.getStream (/srv/node_modules/file-stream-rotator/FileStreamRotator.js:421:5)
    at new DailyRotateFile (/srv/node_modules/winston-daily-rotate-file/daily-rotate-file.js:83:57)
    at configureTransports (/srv/node_modules/parse-server/lib/Adapters/Logger/WinstonLogger.js:41:27)
    at configureLogger (/srv/node_modules/parse-server/lib/Adapters/Logger/WinstonLogger.js:109:3)
    at new WinstonLoggerAdapter (/srv/node_modules/parse-server/lib/Adapters/Logger/WinstonLoggerAdapter.js:19:42)
    at defaultLogger (/srv/node_modules/parse-server/lib/logger.js:24:19)
    at Object.<anonymous> (/srv/node_modules/parse-server/lib/logger.js:28:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)"  
 timestamp: "2019-11-01T17:01:30.067927Z"  
}
 `

### PR DESCRIPTION
**Pull request by dplewis**
Fixes: #6179

Removes unnessary logs.

@kevflynn This PR will allow you to run Parse Server with your configs.

### CODE REVIEW

File: src/logger.js [hunk 1]
```diff
@@ -14,13 +15,17 @@ function defaultLogger() {
...
+let logger;
+const defaultLogger = basicLogger();
 
 export function setLogger(aLogger) {
   logger = aLogger;
 }
 
 export function getLogger() {
+  if (!logger) {
+    return defaultLogger();
```
Comment (acinader) [inline src/logger.js]: do you just want to instantiate the default logger once instead of instantiating a new instance for earch get logger call?

i.e. 

```
if (!logger) {
  logger = defaultLogger();
}
return logger;
```

Comment (dplewis) [reply src/logger.js]: I just noticed that

**Comment by acinader** [comment]
once you remove the log calls from the adapters, is the change in logger.js necessary?

not clear to me what the change in logger.js is doing, or how it addresses the issue.

**Comment by dplewis** [comment]
@acinader This one will need some work. If want to reproduce it see my https://github.com/parse-community/parse-server/issues/6179#issuecomment-549949115

At least we should allow the configurations to be set before crashing. That way silencing the logs can be done.

If you can think of a better fix in the meantime let me know.

**Comment by dplewis** [comment]
@acinader I think this is good to go. If there is an error with winston just use console transport.

**Comment by acinader** [comment]
so even without the logging in the adapters, this still throws?

is there a legitimate case where we could now be 'swallowing' an error? i.e. you want to supress the error when the logger is first referenced, but you will also supress an legitimate error.

is there any way to defer instantiating the logger instead?

**Comment by dplewis** [comment]
@acinader I added a commit with a fix. It no longer throws an error and will use the console as backup.

**Comment by acinader** [comment]
yes, I see the current diff.  I don't see where you're adding the console, or how that'll work.

**Comment by dplewis** [comment]
Its already in there right after the try catch

**Comment by dplewis** [comment]
@kevflynn Can you see if this fixes your issue?
