### PR TITLE
fix: Schema without class level permissions may cause error

### LINKED ISSUE #8406: TypeError: Cannot read property 'protectedFields' of undefined
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

If there are no classLevelPermissions in the schema `perm` below is undefined thus the error. A simple check should fix this issue since a check for `perm` already exist within the `filterSensitiveData` function but I'm not familiar with protectedFields.

https://github.com/parse-community/parse-server/blob/8adc054592769b3f67098a11e715d7066035feed/src/Controllers/DatabaseController.js#L222-L226

### Steps to reproduce

I accidentally ran into this issue while fixing a flaky test on the JS SDK. I don't have a way to reproduce this error server side.

### Actual Outcome

Unhandled promise rejection

### Expected Outcome

No errors

### Environment

Server
- Parse Server version: `6.0.0-alpha.27`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongodb`
- Database version: `4.10.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JS`
- SDK version: `4.0.0`

### PR DESCRIPTION
**Pull request by dplewis**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am creating this PR in reference to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Issue Description

If the schema doesn't have classLevelPermissions for a class an error might occur. I've only seen this happen in very rare edge cases. 

Closes: https://github.com/parse-community/parse-server/issues/8406

### CODE REVIEW

File: src/Controllers/DatabaseController.js [hunk 1]
```diff
@@ -220,8 +220,8 @@ const filterSensitiveData = (
     protectedFields && protectedFields.forEach(k => delete object[k]);
 
     // fields not requested by client (excluded),
-    //but were needed to apply protecttedFields
-    perms.protectedFields &&
+    // but were needed to apply protectedFields
+    perms && perms.protectedFields &&
       perms.protectedFields.temporaryKeys &&
       perms.protectedFields.temporaryKeys.forEach(k => delete object[k]);
```
Comment (mtrezza) [inline src/Controllers/DatabaseController.js]: Since we're on Node >=14 now we can finally use optional chaining.

```suggestion
    perms?.protectedFields?.temporaryKeys?.forEach(k => delete object[k]);
```

**Review by mtrezza — CHANGES_REQUESTED** [review]

File: src/Controllers/DatabaseController.js (hunk 1 above)
Comment (dplewis) [reply src/Controllers/DatabaseController.js]: First use of optional chaining in the entire repo

Comment (mtrezza) [reply src/Controllers/DatabaseController.js]: Deserves a cake!

**Review by mtrezza — APPROVED** [review]
Looks good! Waiting for CI to pass...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.30](https://github.com/parse-community/parse-server/releases/tag/6.0.0-alpha.30)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-server/releases/tag/6.0.0)
