### PR TITLE
Fix/3678 overloaded query constraints

### LINKED ISSUE #3678: doesNotMatchKeyInQuery and equalTo doesn't work in single query if used for same column
### Issue Description

Trying to make query by using doesNotMatchKeyInQuery() and equalTo() on same column fails to produce correct output;

### Steps to reproduce

```
 var query = new Parse.Query("Posts");
 query.equalTo("author", SOME_USER_POINTER);

var banListQuery = new Parse.Query("UserBlockList");
banListQuery.equalTo("blockedUser", req.user);

query.doesNotMatchKeyInQuery("author", "blockedBy", banListQuery);
query.include("author");
query.find();
```

#### Expected Results

Return post of user provided in equalTo() only if requester (req.user) is not blocked by post author;

#### Actual Outcome

equalTo() takes bigger priority and post is returned even if post author has req.user blocked;
Note: not having equalTo() seems to work correctly, blocked users don't see the content;

### Environment Setup

- **Server**
  - parse-server version (Be specific! Don't say 'latest'.) : 2.3.7
  - Operating System:     Ubuntu 16.04
  - Hardware:             8 x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (1 Socket), 8GB Ram
  - Localhost or remote server? (AWS, Heroku, Azure, Digital Ocean, etc): Remote server at OVH

- **Database**
  - MongoDB version: 3.2.12
  - Storage engine: wiredTiger
  - Hardware:       8 x Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (1 Socket), 12GB Ram
  - Localhost or remote server? (AWS, mLab, ObjectRocket, Digital Ocean, etc): OVH

### Logs/Trace

Include all relevant logs. You can turn on additional logging by configuring VERBOSE=1 in your environment.

### PR DESCRIPTION
**Pull request by flovilmart**
Fixes #3678 

Having 2 constraints on the same key when a pointer is set will yield an odd where constraint:

```
author: {
  __type: Pointer,
  objectId: "Author",
  $nin: [...]
}
```

this PR transforms the constraint to:

```
author: {
  $eq: {
    __type: Pointer,
   objectId: "Author",
  }
  $nin: [...]
}
```

In order to be correctly processed.

We should also probably investigate why this happens in the 1st place, the JS SDK handles this in a very odd way.

### CODE REVIEW

File: src/RestQuery.js [hunk 1]
```diff
@@ -438,6 +440,39 @@ const cleanResultAuthData = function (result) {
...
 
+const replaceEqualityConstraint = (constraint) => {
+  if (typeof constraint !== 'object') {
+    return constraint;
+  }
+  const equalToObject = {};
+  let hasDirectConstraint = false;
+  let hasOperatorConstraint = false;
+  for (const key in constraint) {
+    if (key.indexOf('$') != 0) {
```
Comment (acinader) [inline src/RestQuery.js]: !==
