### PR TITLE
fix: LiveQuery server is not shut down properly when `handleShutdown` is called

### LINKED ISSUE #8424: LiveQueryServer doesn't shutdown properly
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

There is a flaky test on the JS SDK and I believe it is caused by the liveQueryServer not shutting down when the server shuts down. The server is shutdown but there are still connections to the liveQueryServer. This may have unwanted effects. Also there are flaky tests on the server that could be addressed
https://github.com/parse-community/Parse-SDK-JS/actions/runs/4011772368/jobs/6889651856

### Steps to reproduce

1) Start server with `startLiveQueryServer: true` configuration
2) Call `server.handleShutdown()`
3) Call `server.close()`
4) Check if live query server is still running

### Actual Outcome

LiveQueryServer is still opened

### Expected Outcome

LiveQueryServer is closed

### Alternatives / Workarounds

In production I use a dedicated live query server instead of the internal configuration which is recommended so I never see this issue.

### Environment

Server
- Parse Server version: `6.0.0`
- Operating system: `Mac`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `Mongo`
- Database version: `4.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `Javascript`
- SDK version: `4.0.0`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

When using `startLiveQueryServer`, the LQ server isn't shutdown after tests. This can be verified with:

```js
const server = await reconfigureServer({
      liveQuery: {
        classNames: ['TestObject'],
      },
      startLiveQueryServer: true,
    });
await server.handleShutdown();
await new Promise(resolve => setTimeout(resolve, 100));
expect(server.liveQueryServer.server.address()).toBeNull(); // liveQuery server has an address
```

Closes: #8424

## Approach

Closes LQ Server at `handleShutdown`

## Tasks

- [x] Add tests

### CODE REVIEW

**Review by dplewis — DISMISSED** [review]
Thanks, LGTM!

**Comment by dplewis** [comment]
@dblythy does the web socket server, pub / sub, and other connections closed as well when the live query server closes?

**Comment by dblythy** [comment]
Good spot, it should now. Is there anything else I should add to the test?

**Comment by dplewis** [comment]
Looks good!

File: src/LiveQuery/ParseLiveQueryServer.js [hunk 1]
```diff
@@ -93,6 +93,21 @@ class ParseLiveQueryServer {
     }
     this._createSubscribers();
   }
+
+  async handleShutdown() {
```
Comment (mtrezza) [inline src/LiveQuery/ParseLiveQueryServer.js]: Would it make sense semantically to call this simply `shutdown` instead of `handleShutdown`? For example, `connect` is also not called `handleConnect`.

**Comment by mtrezza** [comment]
Waiting for CI to pass...

For some reason it seems that no runner is picking up `ci / Check Definitions (pull_request)`. Maybe the ubuntu version is too old - could you try to change it from `ubuntu-18.04` to `ubuntu-latest`?

**Comment by dblythy** [comment]
Addressed in #8503

**Comment by mtrezza** [comment]
Rebasing...

**Comment by mtrezza** [comment]
Could you take a look at the failing definitions check?

File: src/LiveQuery/ParseLiveQueryServer.js (hunk 1 above)
Comment (mtrezza) [reply src/LiveQuery/ParseLiveQueryServer.js]: I just saw that all the related handlers of other adapters are called `handleShutdown`. I think that's an argument to use the same name here. If you agree, could you rename this back?

Comment (dblythy) [reply src/LiveQuery/ParseLiveQueryServer.js]: Well I think your original argument stands and all the other `handleShutdown` calls should just be transitioned to `shutdown`

Comment (mtrezza) [reply src/LiveQuery/ParseLiveQueryServer.js]: Alright, let's leave it then.

**Comment by mtrezza** [comment]
Is this ready for merge?

**Comment by mtrezza** [comment]
@dblythy Is this ready for merge?

**Comment by mtrezza** [comment]
@dblythy is this ready for merge (if CI passes)?

**Comment by dblythy** [comment]
Yep!

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.1.0-alpha.19](https://github.com/parse-community/parse-server/releases/tag/6.1.0-alpha.19)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0](https://github.com/parse-community/parse-server/releases/tag/6.3.0)
