### PR TITLE
fix: Server does not start via CLI when `auth` option is set

### LINKED ISSUE #8665: AuthAdapters cannot be defined by CLI
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases). 

### Issue Description

When starting Parse Server via CLI and with JSON, it's not possible to define auth adapters

### Steps to reproduce

```js
{
  "appName": "test",
  "appId": "test",
  "masterKey": "test",
  "logLevel": "error",
  "auth": {
    "facebook": {
      "appIds": "test"
    }
  }
}

```

### Actual Outcome

`Error: [object Object] should be a comma separated string or an array`

### Environment

Server
- Parse Server version: `alpha`
- Operating system: `macos`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `localhost`

### PR DESCRIPTION
**Pull request by dblythy**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Auth settings cannot be defined by json.

Closes: #8665

## Approach

First commit is a failing test

## Tasks

- [x] Add tests

### CODE REVIEW

**Comment by dblythy** [comment]
https://github.com/parse-community/parse-server/actions/runs/5375104603/jobs/9751171185?pr=8666

Screenshot 2023-06-26 at 5 41 28 pm

**Comment by dblythy** [comment]
@FransGH would you be willing to try this PR out and let us know if it resolves the issue you’ve had?

Let me know if you’d like another PR based on the LTS branch, I’d be happy to sort that out. 

`npm install dblythy/parse-server#fix-auth-parser`

**Comment by FransGH** [comment]
@dblythy thx, I'll try it out on staging now!

**Comment by FransGH** [comment]
@dblythy couldn't get it working yet, likely has nothing to do with the PR. When I replace v5.5.1 with "dblythy/parse-server#fix-auth-parser" I'm getting:

"WARNING, Unable to connect to 'http://localhost:1340/sel'. Cloud code and push notifications may be unavailable"!

Need to go now but will try to get your branch running asap. Is the LTS branch "5.5.x" or what release is your fork based on? 
(I've not yet upgraded to 6.x as I stumbled on other breaking changes)

**Comment by dblythy** [comment]
This PR is based on Parse Server 6, I can pretty easily create another PR based on the LTS branch. I'll have that for you tomorrow.

**Review by mtrezza — CHANGES_REQUESTED** [review]
The Postgres test are consistently failing with:

> 1) execution can start Parse Server with auth via CLI
>   - Error: Timeout - Async function did not complete within 20000ms (set by jasmine.DEFAULT_TIMEOUT_INTERVAL)

File: src/Options/index.js [hunk 1]
```diff
@@ -149,7 +149,7 @@ export interface ParseServerOptions {
   allowCustomObjectId: ?boolean;
   /* Configuration for your authentication providers, as stringified JSON. See http://docs.parseplatform.org/parse-server/guide/#oauth-and-3rd-party-authentication
   :ENV: PARSE_SERVER_AUTH_PROVIDERS */
-  auth: ?(AuthAdapter[]);
+  auth: ?{ [string]: AuthAdapter };
```
Comment (mtrezza) [inline src/Options/index.js:152]: What is this type definition, looks strange to me, how to you read this?

Comment (dblythy) [reply src/Options/index.js:152]: It's meant to be the format:

```js
auth: {
  totp: {
    enabled: true,
    validateLogin() 
  }
}
```

How would you write it?

Comment (mtrezza) [reply src/Options/index.js:152]: Got it now - is this a breaking change though? I assume the server would check the types provided to the `auth` option and wouldn't accept the old type anymore? 

I think we'e already established somewhere else that the current type is incorrect, it shouldn't be an "array of auth adapters" but an "object of auth adapters". Would an option with array of auth adapters still work after this change?

Related: https://github.com/parse-community/parse-server/pull/8535#discussion_r1198492032.

Comment (dblythy) [reply src/Options/index.js:152]: So as far as I can tell, the definitions are only used and validated automatically when Parse Server is started by the CLI (maybe we should address this in #8202). I think this is because the CLI options are by default stringified, and then they are passed to their correct type.

When the auth was changed to an array of auth adapters, the error was not picked up because there isn't any tests to ensure each specific config option is correctly passed through. This was the bug that broke auth adapters for starting via CLI.

Parse Server accesses auth via `auth.facebook` for example, so setting an array of auth adapters wouldn't work, as the array wouldn't have the property "facebook".

So:

- Setting an object of auth adapters wouldn't work before this change (the bug)
- Setting an array of auth adapters wouldn't work before this change (the incorrect change)
- Setting an array of auth adapters wouldn't work after this change (it was never supported)

**Review by mtrezza — APPROVED** [review]
Looks good!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.3.0-alpha.4](https://github.com/parse-community/parse-server/releases/tag/6.3.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-beta.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0-alpha.1](https://github.com/parse-community/parse-server/releases/tag/6.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.4.0](https://github.com/parse-community/parse-server/releases/tag/6.4.0)
