### PR TITLE
Fix mutating beforeSubscribe Query

### LINKED ISSUE #6866: beforeSubscribe doesnt change incoming query
### Issue Description
Hi, Im trying to change the incoming query subscription with Parse.Cloud.beforeSubscribe but im still getting every column at the client. Ive tried changing the subscription query with query.equalTo too but it doesnt have any effect.
I did it the same way as here: [beforeFind](https://docs.parseplatform.org/cloudcode/guide/#find-triggers)
The intention is that some parameter needed for the right subscription shouldnt be displayed in the source code.

**Thats my Cloud code:**
```
Parse.Cloud.beforeSubscribe( 'Chat', ( request ) => {
	if ( !request.user ) {
        throw "Please login before you attempt to connect.";
    }	
	var query = request.query;
        query.select( 'message', 'username' );
	return query;
});
```

**Thats my Client code:**
```
var chat = new Parse.Query( 'Chat' );
chat.subscribe().then(subscription=>{
       subscription.on( 'open', function(){
             console.log( 'Subscription to Chat opened...' );
       });
});
```

###  Environment

Server
- Parse Server version: `4.3.0`
- Operating system: `CentOS 8`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.0.19`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

Client
- SDK (iOS, Android, JavaScript, PHP, Unity, etc): `JavaScript`
- SDK version: `2.15`

### PR DESCRIPTION
**Pull request by dblythy**
Fixes #6866, and now allows returning a new query.

Also adds additional test cases for `beforeSubscribe`. Failing tests are not related to this PR.

@mtrezza, any other tests required to make sure it's 100%?

### CODE REVIEW

File: src/triggers.js [hunk 1]
```diff
@@ -794,7 +794,12 @@ export async function maybeRunSubscribeTrigger(
   parseQuery.withJSON(request.query);
   request.query = parseQuery;
   request.user = await userForSessionToken(request.sessionToken);
-  return trigger(request);
+  const result = (await trigger(request)) || request.query;
+  const query = result.toJSON();
+  if (query.keys) {
+    query.fields = query.keys.split(',');
+  }
+  request.query = query;
```
Comment (dplewis) [inline src/triggers.js:802]: Can you do a check if result.toJSON() exists. What if I return a string or a number. This would throw an error.

File: spec/ParseLiveQuery.spec.js [hunk 2]
```diff
@@ -115,6 +115,95 @@ describe('ParseLiveQuery', function () {
...
+        classNames: ['TestObject'],
+      },
+      startLiveQueryServer: true,
+      verbose: false,
+      silent: true,
+    });
+    Parse.Cloud.beforeSubscribe(TestObject, () => {
+      const query = new Parse.Query(TestObject);
+      query.equalTo('foo', 'yolo');
+      return query;
```
Comment (mtrezza) [inline spec/ParseLiveQuery.spec.js:161]: Do I understand it correctly, that it is possible to return the query but not necessary? That seems strange.

Comment (dplewis) [reply spec/ParseLiveQuery.spec.js:161]: I agree

Comment (mtrezza) [reply spec/ParseLiveQuery.spec.js:161]: @dplewis Didn't I see just a second ago a review comment from you regarding `toJSON`? Did that disappear because I started a review or am I mixing something up here.

Comment (dplewis) [reply spec/ParseLiveQuery.spec.js:161]: I deleted it as it wasn't helpful.

Comment (dblythy) [reply spec/ParseLiveQuery.spec.js:161]: I added it so you can return a different query if required. Is this unnecessary?

Comment (mtrezza) [reply spec/ParseLiveQuery.spec.js:161]: To return a different query I would set `request.query`. Giving the additional option of returning the query unnecessarily occupies the return value of the `beforeSubscribe`, which we could to use for something else in the future.

Comment (dblythy) [reply spec/ParseLiveQuery.spec.js]: Thank you for the feedback @mtrezza, I have removed the return value from `beforeSubscribe` and changed the test case to set `request.query`.

**Comment by dplewis** [comment]
@dblythy Can you rebase from master branch? This will fix the failing tests.

**Comment by dblythy** [comment]
@dplewis thank you for fixing the other tests! Still one test failing for me: 

1) Parse.Push does not get stuck with _PushStatus 'running' on many installations added
  Message:
    Expected 'running' to equal 'succeeded'

Is this related to my PR?

**Comment by mtrezza** [comment]
> Is this related to my PR?

Most likely not. You can try to close and reopen this PR and see whether the test passes. We are having a current issue with intermittently failing test cases which may be the reason this rest fails.

**Comment by davimacedo** [comment]
I believe this PR is failing for Postgres tests.

**Comment by dblythy** [comment]
Any ideas why @davimacedo? The travis-ci logs aren't providing anything useful.

**Comment by davimacedo** [comment]
Nevermind. It was actually intermittently failing.

**Comment by dplewis** [comment]
I restarted the job. Looks good.

**Comment by dblythy** [comment]
Thank you gents!!
