### PR TITLE
fix: Server internal error details leaking in error messages returned to clients

### LINKED ISSUE #8958: Remove detailed error from error messages
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

For some requests, Parse Server returns more information than necessary in the error response. For example:

> unauthorized: master key is required

This is providing an outside attacker with more info than necessary.

### Feature / Enhancement Description

Especially when it comes to access / permission errors, I suggest to make the error messages more ambiguous by generalizing them and removing any specific information. Instead of explaining why a request was unauthorized, the error should be only `unauthorized` without any further details. The detailed error message should only be logged server side.

The task would be:
- identify error messages that should be generalized
- ensure a detailed error message is logged server side

This should not be a breaking change, as long as the error code does not change. Changes of error messages are not considered breaking as logic that relies on parsing error messages is considered bad practice anyway.

### PR DESCRIPTION
**Pull request by coratgerl**
## Pull Request

- Report security issues [confidentially](https://github.com/parse-community/parse-server/security/policy).
- Any contribution is under this [license](https://github.com/parse-community/parse-server/blob/alpha/LICENSE).
- Link this pull request to an [issue](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

## Issue

Fixes: https://github.com/parse-community/parse-server/issues/8958

- [x] Add tests
- [ ] Add changes to documentation (guides, repository pages, code comments)
- [ ] Add [security check](https://github.com/parse-community/parse-server/blob/master/CONTRIBUTING.md#security-checks)
- [ ] Add new Parse Error codes to Parse JS SDK 

## Summary by CodeRabbit

* **New Features**
  * Centralized sanitized-error helpers added so clients now receive a generic "Permission denied" message.

* **Bug Fixes**
  * Internal error details removed from responses while preserving original error codes and behavior.
  * Standardized sanitized error usage for master-key, read-only, auth, and protected-field failures across endpoints.

* **Tests**
  * Tests updated to expect "Permission denied" and to verify sanitized server logs include the original detailed reasons.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by parseplatformorg** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scanner |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/acinader/pr-checks/b856f244-2d6e-49f6-97aa-4b5dc1701af9?refs=75e71488fa9327a4f9dc9d13218adea51720723d&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).

File: src/Controllers/SchemaController.js [hunk 1]
```diff
@@ -1403,15 +1405,11 @@ export default class SchemaController {
     if (perms['requiresAuthentication']) {
       // If aclGroup has * (public)
       if (!aclGroup || aclGroup.length == 0) {
-        throw new Parse.Error(
-          Parse.Error.OBJECT_NOT_FOUND,
-          'Permission denied, user needs to be authenticated.'
-        );
+        const detailedError = 'Permission denied, user needs to be authenticated.';
+        throw createSanitizedError(Parse.Error.OBJECT_NOT_FOUND, detailedError, defaultLogger);
```
Comment (mtrezza) [inline src/Controllers/SchemaController.js]: That's a good concept; could you make this more compact and not add a variable if it's only used in the error obj?


```suggestion
        throw createSanitizedError(
          Parse.Error.OBJECT_NOT_FOUND,
          'Permission denied, user needs to be authenticated.',
          defaultLogger,
        );
```

If the `defaultLogger` is used often, then maybe you can use it as default in the `createSanitizedError` method, so you don't need to pass it every time.

File: src/SecurityError.js [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+  // Keep log on server side
+  log.error('Security error:', detailedMessage);
+
+  const error = new Error();
+  error.status = statusCode;
+  error.message = 'Permission denied';
+  return error;
+}
+
```
[the remark this answers is not in the document]
Comment (coratgerl) [reply src/SecurityError.js]: This function is tested in every test that returs Permission denied

**Comment by mtrezza** [comment]
@coratgerl you can treat coderabbit review comments like human review comments; if you followed it, coderabbit will close its comment after checking your next commit. you should only resolve it manually after providing your arguments. if in doubt you can engage in a discussion. That makes it easier for everyone to know what your position on the feedback is.

File: src/SecurityError.js
Comment (mtrezza) [inline src/SecurityError.js:1]: Rename this file `Error.js` if there isn't one yet, otherwise add to existing file.
Change fie format create 1 export line at the end instead of exporting functions mid file.

File: src/SecurityError.js [hunk 3]
```diff
@@ -0,0 +1,36 @@
...
+ * Creates a sanitized security error from a regular Error object
+ * Used for non-Parse.Error security errors (e.g., Express errors)
+ *
+ * @param {number} statusCode - HTTP status code (e.g., 403)
+ * @param {string} detailedMessage - The detailed error message to log server-side
+ * @param {Object} loggerOrConfig - Optional logger instance or config object
+ * @returns {Error} An Error with sanitized message
+ */
+export function createSanitizedHttpError(statusCode, detailedMessage) {
+  defaultLogger.error('Security error:', detailedMessage);
```
Comment (mtrezza) [inline src/SecurityError.js]: This needs to be rephrased across the whole PR. Let's call this "sanitized error" instead of "security error". Error sanitation can be used for any error that should not go to the requester. In the future, this may include any error parse server sends back, like query errors. There is also no need to prefix "Security error". Instead it should log the error as it is logged currently (pre-PR).

File: src/SharedRest.js [hunk 4]
```diff
@@ -21,14 +23,14 @@ function enforceRoleSecurity(method, className, auth) {
     !auth.isMaster &&
     !auth.isMaintenance
   ) {
-    const error = `Clients aren't allowed to perform the ${method} operation on the ${className} collection.`;
-    throw new Parse.Error(Parse.Error.OPERATION_FORBIDDEN, error);
+    const detailedError = `Clients aren't allowed to perform the ${method} operation on the ${className} collection.`;
+    throw createSanitizedError(Parse.Error.OPERATION_FORBIDDEN, detailedError);
```
Comment (mtrezza) [inline src/SharedRest.js]: Combine

File: src/SharedRest.js [hunk 5]
```diff
@@ -21,14 +23,14 @@ function enforceRoleSecurity(method, className, auth) {
...
   }
 
   // readOnly masterKey is not allowed
   if (auth.isReadOnly && (method === 'delete' || method === 'create' || method === 'update')) {
-    const error = `read-only masterKey isn't allowed to perform the ${method} operation.`;
-    throw new Parse.Error(Parse.Error.OPERATION_FORBIDDEN, error);
+    const detailedError = `read-only masterKey isn't allowed to perform the ${method} operation.`;
+    throw createSanitizedError(Parse.Error.OPERATION_FORBIDDEN, detailedError);
```
Comment (mtrezza) [inline src/SharedRest.js]: Combine

File: spec/AudienceRouter.spec.js [hunk 6]
```diff
@@ -269,7 +269,7 @@ describe('AudiencesRouter', () => {
     }).then(
       () => {},
       error => {
-        expect(error.message).toEqual('unauthorized: master key is required');
+        expect(error.message).toEqual('Permission denied');
```
Comment (mtrezza) [inline spec/AudienceRouter.spec.js:280]: All the modified tests across the PR require an additional `expect` for the logged full error message.

File: spec/schemas.spec.js [hunk 7]
```diff
@@ -2557,7 +2557,7 @@ describe('schemas', () => {
           return Promise.resolve();
         },
         err => {
-          expect(err.message).toEqual('Permission denied for action find on class AClass.');
+          expect(err.message).toEqual('Permission denied');
```
Comment (mtrezza) [inline spec/schemas.spec.js:2591]: Can we test more than only the error message? What about the error code?

File: src/Controllers/SchemaController.js [hunk 8]
```diff
@@ -1403,15 +1405,11 @@ export default class SchemaController {
...
-        );
+        const detailedError = 'Permission denied, user needs to be authenticated.';
+        throw createSanitizedError(Parse.Error.OBJECT_NOT_FOUND, detailedError);
       } else if (aclGroup.indexOf('*') > -1 && aclGroup.length == 1) {
-        throw new Parse.Error(
-          Parse.Error.OBJECT_NOT_FOUND,
-          'Permission denied, user needs to be authenticated.'
-        );
+        const detailedError = 'Permission denied, user needs to be authenticated.';
+        throw createSanitizedError(Parse.Error.OBJECT_NOT_FOUND, detailedError);
```
Comment (mtrezza) [inline src/Controllers/SchemaController.js]: Combine

File: src/Controllers/SchemaController.js [hunk 9]
```diff
@@ -1403,15 +1405,11 @@ export default class SchemaController {
     if (perms['requiresAuthentication']) {
       // If aclGroup has * (public)
       if (!aclGroup || aclGroup.length == 0) {
-        throw new Parse.Error(
-          Parse.Error.OBJECT_NOT_FOUND,
-          'Permission denied, user needs to be authenticated.'
-        );
+        const detailedError = 'Permission denied, user needs to be authenticated.';
+        throw createSanitizedError(Parse.Error.OBJECT_NOT_FOUND, detailedError);
```
Comment (mtrezza) [inline src/Controllers/SchemaController.js]: Combine

File: src/Controllers/SchemaController.js [hunk 10]
```diff
@@ -1425,10 +1423,8 @@ export default class SchemaController {
 
     // Reject create when write lockdown
     if (permissionField == 'writeUserFields' && operation == 'create') {
-      throw new Parse.Error(
-        Parse.Error.OPERATION_FORBIDDEN,
-        `Permission denied for action ${operation} on class ${className}.`
-      );
+      const detailedError = `Permission denied for action ${operation} on class ${className}.`;
+      throw createSanitizedError(Parse.Error.OPERATION_FORBIDDEN, detailedError);
```
Comment (mtrezza) [inline src/Controllers/SchemaController.js]: Combine

File: src/Controllers/SchemaController.js [hunk 11]
```diff
@@ -1448,10 +1444,8 @@ export default class SchemaController {
       }
     }
 
-    throw new Parse.Error(
-      Parse.Error.OPERATION_FORBIDDEN,
-      `Permission denied for action ${operation} on class ${className}.`
-    );
+    const detailedError = `Permission denied for action ${operation} on class ${className}.`;
+    throw createSanitizedError(Parse.Error.OPERATION_FORBIDDEN, detailedError);
```
Comment (mtrezza) [inline src/Controllers/SchemaController.js]: Combine

File: src/TestUtils.js
Comment (mtrezza) [inline src/TestUtils.js:1]: Is this helper really necessary? Why not spy on logger and check the calls in the `expect`?

Comment (coratgerl) [reply src/TestUtils.js:1]: you can have multiple calls of the logger in a test so we need to get the correct call. This is why I get the number of call just before the operation.

Maybe there is an another solution, but not sure to see how

Comment (mtrezza) [reply src/TestUtils.js:1]: I don't understand what you are trying to achieve. Why not spy on the logger once for all the tests, then reset the calls before executing what should trigger the log, then do a simple match across all spy calls for the expected message?

Comment (coratgerl) [reply src/TestUtils.js:1]: Ok understand what you mean !

File: spec/AudienceRouter.spec.js [hunk 12]
```diff
@@ -263,55 +263,75 @@ describe('AudiencesRouter', () => {
...
+        expect(loggerErrorSpy).toHaveBeenCalledWith('Sanitized error:', jasmine.stringContaining('unauthorized: master key is required'));
         done();
       }
     );
   });
 
   it('should only find with master key', done => {
+    const logger = require('../lib/logger').default;
+    const loggerErrorSpy = spyOn(logger, 'error').and.callThrough();
```
Comment (mtrezza) [inline spec/AudienceRouter.spec.js]: Move this outside the tests, to the top of the root describe block; only needs to be done once.

Comment (coratgerl) [reply spec/AudienceRouter.spec.js]: We need to do this in a beforeEach because some elements in the tests (I identified reconfigureServer, but there are others I haven’t identified yet) reset the logger. We need to re-require the default logger to ensure it works correctly.
I tried using a beforeAll, but it didn’t work, which is why I implemented it in each test. However, a beforeEach solution might be a good alternative

File: src/rest.js [hunk 13]
```diff
@@ -326,7 +327,9 @@ function handleSessionMissingError(error, className, auth) {
     !auth.isMaster &&
     !auth.isMaintenance
   ) {
-    throw new Parse.Error(Parse.Error.SESSION_MISSING, 'Insufficient auth.');
+    const { createSanitizedError } = require('./Error');
```
Comment (mtrezza) [inline src/rest.js]: Move require to top of file

File: src/RestQuery.js [hunk 14]
```diff
@@ -7,6 +7,8 @@ const triggers = require('./triggers');
 const { continueWhile } = require('parse/lib/node/promiseUtils');
 const AlwaysSelectedKeys = ['objectId', 'createdAt', 'updatedAt', 'ACL'];
 const { enforceRoleSecurity } = require('./SharedRest');
+const { createSanitizedError } = require('./Error');
+const defaultLogger = require('./logger').default;
```
Comment (mtrezza) [inline src/RestQuery.js]: Why is this defaultLogger require needed?

File: src/RestWrite.js [hunk 15]
```diff
@@ -199,9 +201,11 @@ RestWrite.prototype.validateClientClassCreation = function () {
       .then(schemaController => schemaController.hasClass(this.className))
       .then(hasClass => {
         if (hasClass !== true) {
-          throw new Parse.Error(
+          const log = (this.config && this.config.loggerController) || defaultLogger;
```
Comment (mtrezza) [inline src/RestWrite.js]: @coderabbitai Why is it only here that we're using the `config.loggerController || defaultLogger`, and not in all other places as well? What's the purpose of this?

Comment (mtrezza) [reply src/RestWrite.js]: @coratgerl ?

Comment (coratgerl) [reply src/RestWrite.js]: CR is right this is a remnant of my previous commit.

**Review by mtrezza — COMMENTED** [review]
Looks good, just the failing lint

File: src/RestQuery.js [hunk 16]
```diff
@@ -51,7 +52,7 @@ async function RestQuery({
     throw new Parse.Error(Parse.Error.INVALID_QUERY, 'bad query type');
   }
   const isGet = method === RestQuery.Method.get;
-  enforceRoleSecurity(method, className, auth);
+  enforceRoleSecurity(method, className, auth, config);
```
Comment (mtrezza) [inline src/RestQuery.js]: @coderabbitai what effect does this change have, any why was it likely made?

Comment (mtrezza) [reply src/RestQuery.js]: @coderabbitai in src/SharedRest.js the method has only 3 params: `enforceRoleSecurity(method, className, auth)`

cc @coratgerl

**Review by mtrezza — APPROVED** [review]

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.5.0-alpha.13](https://github.com/parse-community/parse-server/releases/tag/8.5.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [8.5.0](https://github.com/parse-community/parse-server/releases/tag/8.5.0)
